# Generated by Django 5.0.7 on 2024-07-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзина",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Количество"
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт в корзине",
                "verbose_name_plural": "Продукты в корзине",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=254,
                        unique=True,
                        verbose_name="Имя категории",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        db_index=False,
                        max_length=254,
                        unique=True,
                        verbose_name="Адрес категории",
                    ),
                ),
                (
                    "image_field",
                    models.ImageField(
                        upload_to="", verbose_name="Изображение категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=254,
                        unique=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        db_index=False,
                        max_length=254,
                        unique=True,
                        verbose_name="Адрес товара",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена")),
                (
                    "image_small",
                    models.ImageField(
                        upload_to="", verbose_name="Маленькое изображение"
                    ),
                ),
                (
                    "image_medium",
                    models.ImageField(
                        upload_to="", verbose_name="Среднее изображение"
                    ),
                ),
                (
                    "image_large",
                    models.ImageField(
                        upload_to="", verbose_name="Большое изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=254,
                        unique=True,
                        verbose_name="Имя подкатегории",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        db_index=False,
                        max_length=254,
                        unique=True,
                        verbose_name="Адрес подкатегории",
                    ),
                ),
                (
                    "image_field",
                    models.ImageField(
                        upload_to="", verbose_name="Изображение подкатегории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
    ]
